# Generated by Django 5.0.4 on 2024-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remained_quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
