# Generated by Django 5.0.4 on 2024-05-25 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_remained_quantity_product_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timeadded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='remained_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
