# Generated by Django 5.0.4 on 2024-05-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_timeadded_alter_product_remained_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timeadded',
            new_name='pub_date',
        ),
    ]
